// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:slaptask/data/models/app_settings.dart';
import 'package:slaptask/data/models/day_tasks.dart';
import 'package:slaptask/data/models/task.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(DayTasksAdapter());
    registerAdapter(TaskAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(DayTasksAdapter());
    registerAdapter(TaskAdapter());
  }
}
